---
- name: Creates /mnt only required in one large volume
  file: 
    path: /mnt 
    state: directory
    mode: "u=rwx,g=wx,o=rwx"

- name: Configuring RBACK for Tiller Deployment
  shell: kubectl create -f /home/ubuntu/ONAP_LAB/deploy/roles/k8s/tiller-serviceaccount.yaml

- name: Initialize Tiller
  shell: helm init --service-account tiller --upgrade

- name: sleep for 180 seconds and continue with play
  wait_for: timeout=180
  delegate_to: localhost

- name: Collect Helm Charts
  become: yes
  git:
    repo: https://git.onap.org/oom/
    dest: /mnt/srv/oom
    clone: yes

- name: Start Helm Server
  shell: sudo helm serve >/dev/null 2>&1 &

- name: Add local Helm Repo for Charts
  shell: sudo helm repo add local http://127.0.0.1:8879

- name: Remove Default Helm Repo
  shell: sudo helm repo remove stable

- name: Helm List Repo
  shell: sudo helm repo list

- name: Install demo template
  become: yes
  template:
      src: "{{ config }}"
      dest: /mnt/srv/oom/kubernetes/onap/values.yaml

- name: Ingest Charts to the Helm Local Repo
  command: sudo make all
  args:
    chdir: /mnt/srv/oom/kubernetes

- name: Creates dockerdata-nfs
  file: 
    path: /mnt/dockerdata-nfs 
    state: directory
    mode: "u=rwx,g=wx,o=rwx"

#- name: Install The Helm Repo - Not current available
#  shell: helm install osn/onap

- name: sleep for 180 seconds before continue with ONAP Deployment
  wait_for: timeout=180
  delegate_to: localhost

- name: Deploying ONAP Helm
  shell: sudo helm install local/onap -n dev --namespace onap 

